### ISSUE TITLE
Error on Launch: Unauthorised Launch of Enviromine

### ISSUE THREAD

**Issue by Charlotteis** [C222/LadPack#5]
Hi!

Trying to Launch Lad-Pack from Technic and getting the following:
- Minecraft window opens, but is a black screen.
- Crashes,
- Logs have the following:

Description: Initializing game

java.lang.SecurityException: UNAUTHORIZED USE OF MOD ENVIROMINE

**Comment by Charlotteis** [comment]
I found the files that this error comes from by the way :)

https://github.com/EnviroMine/EnviroMine-1.7/blob/4a89ea97bcdab21efdfe896367ba64c63b492a6f/src/main/java/enviromine/utils/LockedClass.java

https://github.com/EnviroMine/EnviroMine-1.7/blob/50c9780d71e42cfd3d740ba9dd8513bad4c7969a/src/main/java/enviromine/core/FunwayModAuthentication.java

**Comment by C222** [comment]
If people download the modpack when the version of Enviromine isn't up-to-date, the auth fails. I'll try my best to keep the pack's version the latest.
